services:
  api-pacientes:
    container_name: api-pacientes
    image: datospacientes-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    # --- Red Bridge Explícita ---
    networks:
      - pacientes-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      # SUSTITUYE con los datos reales de tu servidor de BD (IP, DB, User, Pass)
      - ConnectionStrings__cnDatabase=Server=192.168.1.XX,1433;Database=NombreDB;User Id=Usuario;Password=Contraseña;TrustServerCertificate=True
      # Configuración de Keycloak
      - Keycloak__Authority=http://192.168.1.YY:8080/realms/master
      - Keycloak__Audience=api-pacientes
    ports:
      - "8080:80"
    restart: always

# Definición de la red bridge
networks:
  pacientes-net:
    driver: bridge
