services:
  api-pacientes:
    container_name: api-pacientes
    image: datospacientes-api:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - hro-net
    volumes:
      - dp-keys:/root/.aspnet/DataProtection-Keys
    restart: always

networks:
  hro-net:
    external: true

volumes:
   dp-keys: