services:
  api-pacientes:
    container_name: api-pacientes
    image: datospacientes-api:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - pacientes-net
    ports:
      - "8081:8080"
    volumes:
      - dp-keys:/root/.aspnet/DataProtection-Keys
    restart: always

networks:
  pacientes-net:
    driver: bridge

volumes:
   dp-keys: